//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulo
    {
        public int id_articulo { get; set; }
        public string ANombre { get; set; }
        public double APrecio { get; set; }
        public int Categoria_id_categoria { get; set; }
    
        public virtual Categoria Categoria { get; set; }
    }
}
